
//! Autogenerated weights for `pallet_nft`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-09, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_nft
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --json
// --output
// ./pallets/nft/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
	fn mint_nft() -> Weight;
	fn create_collection() -> Weight;
	fn edit_nft() -> Weight;
	fn edit_collection() -> Weight;
	fn destroy_collection() -> Weight;
	fn buy_nft() -> Weight;
	fn set_sale_nft() -> Weight;
	fn set_nft_price() -> Weight;
	fn burn_nft() -> Weight;
	fn pay_installment() -> Weight;
}

/// Weight functions for `pallet_nft`.
pub struct SubstrateWeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeightInfo<T> {
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: PalletNFT TokenById (r:1 w:1)
	fn mint_nft() -> Weight {
		(55_109_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: PalletNFT CollectionById (r:1 w:1)
	fn create_collection() -> Weight {
		(48_242_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PalletNFT CollectionById (r:1 w:1)
	// Storage: PalletNFT TokenById (r:1 w:0)
	fn destroy_collection() -> Weight {
		(29_248_000 as Weight)
			// Standard Error: 1_000
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PalletNFT TokenById (r:1 w:1)
	fn edit_nft() -> Weight {
		(46_463_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PalletNFT CollectionById (r:1 w:1)
	fn edit_collection() -> Weight {
		(42_804_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PalletNFT TokenById (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn buy_nft() -> Weight {
		(60_150_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: PalletNFT TokenById (r:1 w:1)
	// Storage: PalletNFT OrderByTokenId (r:1 w:1)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	fn pay_installment() -> Weight {
		(64_049_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: PalletNFT TokenById (r:1 w:1)
	fn set_sale_nft() -> Weight {
		(25_515_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PalletNFT TokenById (r:1 w:1)
	fn set_nft_price() -> Weight {
		(27_620_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PalletNFT TokenById (r:1 w:1)
	fn burn_nft() -> Weight {
		(24_759_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}

impl WeightInfo for () {
	fn mint_nft() -> Weight {
		(36_924_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	fn create_collection() -> Weight {
		(28_085_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	fn edit_nft() -> Weight {
		(26_579_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	fn edit_collection() -> Weight {
		(23_809_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	
	fn destroy_collection() -> Weight {
		(29_248_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	fn buy_nft() -> Weight {
		(72_734_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	fn set_sale_nft() -> Weight {
		(27_405_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	fn set_nft_price() -> Weight {
		(28_423_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	fn burn_nft() -> Weight {
		(32_354_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	fn pay_installment() -> Weight {
		(64_049_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
}