
//! Autogenerated weights for `pallet_nft`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-09, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_nft
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --json
// --output
// ./pallets/nft/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
	fn mint_nft() -> Weight;
	fn edit_nft() -> Weight;
	fn buy_nft() -> Weight;
	fn set_sale_nft() -> Weight;
	fn set_nft_price() -> Weight;
	fn burn_nft() -> Weight;
}

/// Weight functions for `pallet_nft`.
pub struct SubstrateWeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeightInfo<T> {
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: PalletNFT TokenById (r:1 w:1)
	fn mint_nft() -> Weight {
		(34_588_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PalletNFT TokenById (r:1 w:1)
	fn edit_nft() -> Weight {
		(27_222_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PalletNFT TokenById (r:1 w:1)
	// Storage: PalletNFT TokenSale (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn buy_nft() -> Weight {
		(68_628_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: PalletNFT TokenById (r:1 w:0)
	// Storage: PalletNFT TokenSale (r:1 w:1)
	fn set_sale_nft() -> Weight {
		(27_083_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PalletNFT TokenById (r:1 w:0)
	// Storage: PalletNFT TokenSale (r:1 w:1)
	fn set_nft_price() -> Weight {
		(32_756_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: PalletNFT TokenById (r:1 w:1)
	// Storage: PalletNFT TokenSale (r:1 w:0)
	fn burn_nft() -> Weight {
		(27_342_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}

impl WeightInfo for () {
	fn mint_nft() -> Weight {
		(34_588_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	fn edit_nft() -> Weight {
		(27_222_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	fn buy_nft() -> Weight {
		(68_628_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	fn set_sale_nft() -> Weight {
		(27_083_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	fn set_nft_price() -> Weight {
		(32_756_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}

	fn burn_nft() -> Weight {
		(27_342_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
}